# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "509d6eb2c05b772fc55e35b863c8db1a"
name = "invoice-generator-prod"
handle = "invoice-generator-prod"
application_url = "https://vinyl-promised-solution-displaying.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_products"

[auth]
redirect_urls = ["https://vinyl-promised-solution-displaying.trycloudflare.com/auth/callback", "https://vinyl-promised-solution-displaying.trycloudflare.com/auth/shopify/callback", "https://vinyl-promised-solution-displaying.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
